<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['destinations'] = [
    [
        'title' => 'Brighton Transfer',
        'metaDescription' => '24/7 Brighton airport taxi & transfer services to Gatwick, Heathrow & all UK airports. Fixed rates, executive cars, hassle-free travel every time.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/brighton-transfer',
        'slug' => 'brighton-transfer',
        'ogTitle' => 'Brighton Transfer – Comfortable & Reliable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your Brighton taxi transfer with Travel 24 Taxi. Affordable prices, professional drivers, and 24/7 availability for your convenience',
        'ogUrl' => 'ogUrl',
        'heading' => 'Brighton Transfer',
        'subHeading' => 'Book a private-hire from Brighton to elsewhere in the UK through our Brighton  transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our taxi service around Brighton would ensure you’re having a seamless ride  from Brighton to other locations in the UK and vice versa. ',
        'content2' => ' Our reliable service is also affordable and easy to access. You can simply book your ride through our online booking system, and get your transfer quote instantly..',
        'content3' => ''
    ],
    [
        'title' => 'Bristol Transfer',
        'metaDescription' => 'Reliable Bristol airport taxi transfers to any UK destination. Affordable prices, 24/7 service. Book now for a smooth, on-time airport journey.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/bristol-transfer',
        'slug' => 'bristol-transfer',
        'ogTitle' => 'Bristol Transfer – Reliable & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your hassle-free Bristol taxi transfer with Travel 24 Taxi. Professional drivers and 24/7 availability at competitive prices',
        'ogUrl' => 'ogUrl',
        'heading' => 'Bristol transfer',
        'subHeading' => 'Book a private-hire from Bristol  to elsewhere in the UK through our Bristol transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Want a hassle-free travel from or to Bristol?  ',
        'content2' => 'Book a private hire at Travel24 Bristol transfer. We provide affordable travel solutions, tailored to passengers who want to reach their destination on time. We make this possible with our experienced drivers and customized vehicles. Our fleet includes  8-seater Minibus (Van) and mobility vehicles like cars,cabs etc.',
        'content3' => 'You can easily get access to our services by getting an online transfer quote  through our online booking system available at our official website.'
    ],
    [
        'title' => 'Gatwick Airport Transfer',
        'metaDescription' => 'Book reliable, low-cost Gatwick Airport taxi transfers. 24/7 service, fixed fares, professional drivers, and easy online booking!',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/gatwick-airport-transfer',
        'slug' => 'gatwick-airport-transfer',
        'ogTitle' => 'Gatwick Airport Transfer – Comfortable & Reliable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your Gatwick Airport taxi transfer with Travel 24 Taxi. Professional drivers, competitive prices, and 24/7 availability for a stress-free journey.',
        'ogUrl' => 'ogUrl',
        'heading' => 'Gatwick Airport transfer',
        'subHeading' => 'Book a private-hire from Gatwick to elsewhere in the UK through our Gatwick transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our Airport transfer service from and to Gatwick airport is the best transportation service you can find around the place. Our services are available 24/7 and it is also affordable and reliable. ',
        'content2' => ' We are also well-equipped with a  variety of cars/cabs and experienced drivers. Our services are tailored to meet  the needs of the number of passengers and luggage requirements. ',
        'content3' => 'We  understand the passengers’ need to reach the airport and other destinations on time, so we work hard to ensure a dependable experience for all passengers. You can easily book your ride through our online booking system available on our website.'
    ],
    [
        'title' => 'Guildford Transfer',
        'metaDescription' => 'Reliable Guildford airport taxi service to all major UK airports. Book online 24/7 for fast, affordable, and trusted airport transfers.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/guildford-transfer',
        'slug' => 'guildford-transfer',
        'ogTitle' => 'Guildford Transfer – Reliable & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your convenient Guildford taxi transfer with Travel 24 Taxi. Professional drivers and 24/7 service for a smooth ride',
        'ogUrl' => 'ogUrl',
        'heading' => 'Guilford transfer',
        'subHeading' => 'Book a private-hire from Guilford to elsewhere in the UK through our Guilford  transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our Guilford transfer services offers affordable travel options to and from Guilford to anywhere in the Uk. Our services are highly affordable and reliable. ',
        'content2' => 'We make sure you reach your destinations on time and safely. Our drivers are experienced professionals who will assist you at their earliest to ensure you have a seamless journey. Our services are tailored to meet the specific needs of the passengers including their luggage requirements. Our services are available 24/7 and accessible. ',
        'content3' => 'You can get an instant transfer quote and book your ride through our online  booking system available at our official website'
    ],
    [
        'title' => 'Heathrow Airport Transfer',
        'metaDescription' => 'Heathrow Airport Transfer made easy. Book reliable, 24/7 taxi or private hire service with fixed fares to and from any terminal in London hassle-free.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/heathrow-airport-transfer',
        'slug' => 'heathrow-airport-transfer',
        'ogTitle' => 'Heathrow Airport Transfer – Reliable & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your hassle-free Heathrow Airport taxi transfer with Travel 24 Taxi. Professional drivers and 24/7 availability for your convenience',
        'ogUrl' => 'ogUrl',
        'heading' => 'Heathrow Airport Transfer - Reliable and Comfortable Transfer Service',
        'subHeading' => 'London Heathrow Transfer services offer seamless chauffeur and private-hire vehicle bookings from Heathrow Airport to any destination across the UK. Our diverse fleet—including 8-seater minibuses, mobility vehicles, and more—is designed to meet the needs of every passenger.',
        'content1' => 'Our airport transfer service to and from Heathrow Airport offers an affordable and top-quality private-hire experience. We are reliable, experienced, and committed to delivering quality travel solutions in Heathrow at the best prices. We understand that passengers often worry about reaching the airport and other destinations on time, so we work hard to ensure you arrive safely and punctually. ',
        'content2' => 'Our services extend from Heathrow to London and other popular locations, offering convenient travel options. We are well-equipped with a variety of cars/cabs and experienced drivers. Services are tailored to meet the needs of the number of passengers and luggage requirements.',
        'content3' => 'You can book your ride through our online booking system by simply entering your details and getting your transfer quote instantly on our website.'
    ],
    [
        'title' => 'Luton Airport Transfer',
        'metaDescription' => 'Affordable, reliable Luton Airport taxi transfers. 24/7 service from London & beyond. Fixed fares with professional drivers and on-time pickup guaranteed .',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/luton-airport-transfer',
        'slug' => 'luton-airport-transfer',
        'ogTitle' => 'Luton Airport Transfers - Travel 24 Taxi',
        'ogDescription' => 'Need a ride to or from Luton Airport? Travel 24 Taxi offers dependable airport transfer services with 24/7 availability and professional drivers',
        'ogUrl' => 'ogUrl',
        'heading' => 'Luton airport transfer',
        'subHeading' => 'Book a private-hire from Luton to elsewhere in the UK through our Luton transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our Luton airport transfer service offers affordable travel options to Luton airport and from Luton airport to Bedfordshire and elsewhere in the country. ',
        'content2' => ' We offer travel solutions at best rates and our experienced drivers at Travel24 will make sure you reach the airport and other destinations in style. Our services are also tailored to meet the needs of the number of passengers and luggage requirements. ',
        'content3' => 'You can book your ride through our online booking system by simply entering your details and getting your transfer quote instantly on our website.'
    ],
    [
        'title' => 'London Transfer',
        'metaDescription' => 'Book reliable London airport transfers to/from Heathrow, Gatwick, Stansted & more. Private, on-time service with fixed rates. Travel stress-free today!',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/london-transfer',
        'slug' => 'london-transfer',
        'ogTitle' => 'London Transfer – Professional & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your London taxi transfer with Travel 24 Taxi for reliable, comfortable rides at competitive prices. Available 24/7 with experienced drivers',
        'ogUrl' => 'ogUrl',
        'heading' => 'London transfer',
        'subHeading' => 'Book a private-hire from London to elsewhere in the UK through our London transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Whether you want to go  to London  or from London to other  popular destinations around the UK, our London transfer  services will offer affordable travel solutions tailored to your specific needs and requirements ',
        'content2' => '. Our experienced  drivers will make sure that you reach the relevant destination in style and all your travel needs are met. We are also well equipped with a variety of mobility vehicles  which are designed to cater to the specific needs of the passengers such as luggage requirements. Our services are reliable and available any time. ',
        'content3' => 'Our services are reliable and available any time. Our services are also easy to access . You can book your ride now by entering your pickup location and destination and get an instant transfer quote at our official website.'
    ],
    [
        'title' => 'London City Airport Transfer ',
        'metaDescription' => 'Book your London City Airport transfer with Travel24Taxi. Fast, reliable, and affordable taxi service for a smooth, hassle-free ride to or from the airport.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/London-city-airport-transfer',
        'slug' => 'London-city-airport-transfer',
        'ogTitle' => 'London City Airport Transfer – Reliable & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your hassle-free London City Airport taxi transfer with Travel 24 Taxi. Affordable rates, professional drivers, and 24/7 service',
        'ogUrl' => 'ogUrl',
        'heading' => 'London City Airport Transfer',
        'subHeading' => 'Book a private-hire from London City to elsewhere in the UK through our London City transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our London airport transfer service offers top-end ervices to and from London airport to other locations for best rates ',
        'content2' => ' Our services are tailored to meet the needs of the passengers. including the number of passengers and their luggage requirements. Our reliable services are available 24/7 and our fleet consists tailored vehicles to suit the specific needs of the passengers.',
        'content3' => ' We understand that Airport transfers evolves around time, so we make sure to work on time for the benefit of our customers.Our xperienced drivers on the other hand will make sure you reach your destination on time and safely. You can easily access our services through our online booking system available on our website.'
    ],
    [
        'title' => 'Maidenhead Transfer',
        'metaDescription' => 'Reliable 24/7 Maidenhead taxi service. Airport transfers, private hire, minibus, and executive cars. Book online or call for fixed-price quotes.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/maidenhead-transfer',
        'slug' => 'maidenhead-transfer',
        'ogTitle' => 'Maidenhead Transfer – Comfortable & Reliable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your convenient and affordable Maidenhead taxi transfer with Travel 24 Taxi. 24/7 service and professional drivers at your service',
        'ogUrl' => 'ogUrl',
        'heading' => 'Maidenhead transfer',
        'subHeading' => 'Book a private-hire from Maidenhead  to elsewhere in the UK through our Maidenhead  transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Want a hassle-free travel from or to Maidenhead?   ',
        'content2' => 'Book a private hire at Travel24 Maidenhead transfer. We provide affordable travel solutions tailored to passengers’ specific needs.We also make sure our passengers reach their destination on time. We make this possible with our experienced drivers and our customized vehicles. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicles such as cars, cabs etc., to serve the purpose of the passengers. ',
        'content3' => 'You can easily get access to our services by getting an online transfer quote through our online booking system available at our official website.'
    ],
    [
        'title' => 'Oxford Transfer',
        'metaDescription' => 'Oxford airport transfers, taxis & chauffeur service. Fixed prices, 24/7 availability & clean cars. Book online for travel to all major UK airports.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/oxford-transfer',
        'slug' => 'oxford-transfer',
        'ogTitle' => 'Oxford Airport Transfers - Travel 24 Taxi',
        'ogDescription' => 'Book a reliable taxi to or from Oxford with Travel 24 Taxi. 24/7 service, professional drivers, and competitive rates for airport transfers.',
        'heading' => 'Oxford Transfer',
        'subHeading' => 'Book a private-hire from Oxfordto to elsewhere in the UK through our Oxfordtransfer Transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our Oxfords transfer service to and from Oxford is the most reliable and cost-effective option available.Our services are tailored to meet the specific needs of the passengers such as luggage requirements.   ',
        'content2' => 'Our fleet includes variety of vehicles such as  8-Seater Minibus (Van), Mobility Vehicles such as cars, cabs etc., which are designed to suit the needs of the passengers who want a seamless ride with convenience.',
        'content3' => ' Our services are available 24/7 and also accessible. Book your ride through our online booking system available on our website and get a quote instantly.'
    ],
    [
        'title' => 'Southampton Transfer',
        'metaDescription' => 'Book reliable Southampton airport & cruise taxi transfers. 24/7 service, private hire & chauffeur cars. Low fixed rates. Easy online booking available',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/southampton-transfer',
        'slug' => 'southampton-transfer',
        'ogTitle' => 'Southampton Transfer – Trusted & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your reliable Southampton taxi transfer with Travel 24 Taxi. Professional drivers, competitive prices, and 24/7 availability.',
        'ogUrl' => 'ogUrl',
        'heading' => 'Southampton Transfer',
        'subHeading' => 'Book a private-hire from Southampton to  elsewhere in the UK through our Southampton Transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our taxi service around Southampton would ensure you’re having a seamless ride from Southampton to other locations in the UK and vice versa ',
        'content2' => '. Our reliable service is also affordable and easy to access. You can simply book your ride through our online booking system and get your transfer quote instantly on our website. ',
        'content3' => 'We provide tailored travel solutions for the specific needs of the passengers. Our variety of vehicles are designed to suit the luggage requirements of the passengers and our experienced drivers will make sure you reach the relevant destination in style.'
    ],
    [
        'title' => 'Stansted Airport Transfer',
        'metaDescription' => 'Stansted Airport taxi & transfer service. 24/7 private hire, meet & greet, minibuses, fixed rates & online booking. Fast, reliable travel to/from London.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/stansted-airport-transfer',
        'slug' => 'stansted-airport-transfer',
        'ogTitle' => 'Stansted Airport Transfer – Convenient & Affordable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your reliable Stansted Airport taxi transfer with Travel 24 Taxi. Professional drivers and 24/7 service for a stress-free journey',
        'ogUrl' => 'ogUrl',
        'heading' => 'Stansted Airport Transfer',
        'subHeading' => 'Book a private-hire from Stansted to elsewhere in the UK through our Stansted Transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our airport transfer service to and from Stansted Airport offers an affordable and top-quality private-hire experience. ',
        'content2' => ' We are reliable, experienced, and committed to delivering quality travel solutions for best prices. Concerning the necessity of the passengers, we work hard to ensure they arrive safely and punctually.Our fleet is well-equipped with a variety of cars and cabs, driven by experienced professionals.Our services are tailored to meet the needs of the number of passengers and luggage requirements. ',
        'content3' => 'You can book your ride through our online booking system by simply entering your details  and getting your transfer quote instantly on our website.'
    ],
    [
        'title' => 'Windsor Transfer',
        'metaDescription' => 'Windsor taxi & airport transfer service. 24/7 local & long-distance rides, fixed fares, meet & greet, saloon to minibus. Book online for all major airports.',
        'canonicalLink'=>'https://travel24taxi.com/popularDestinations/view/windsor-transfer',
        'slug' => 'windsor-transfer',
        'ogTitle' => 'Windsor Transfer – Reliable & Comfortable Taxi Service | Travel 24 Taxi',
        'ogDescription' => 'Book your Windsor taxi transfer with Travel 24 Taxi for a hassle-free and affordable journey. Available 24/7 with professional drivers',
        'ogUrl' => 'ogUrl',
        'heading' => 'Windsor Transfer',
        'subHeading' => 'Book a private-hire from Windsor to elsewhere in the UK through our Windsor Transfer services. Our fleet includes 8 Seater Minibus (Van), Mobility Vehicle  (cars, cabs etc.), to serve the purpose of the passengers.',
        'content1' => 'Our Windsor transfer service is the most reliable and cost-effective option available. We tailor our services to meet the specific needs of our passengers, including luggage requirements. ',
        'content2' => 'Our drivers are experienced individuals who are committed to providing quality services and satisfactory travel experiences.  
Our fleet includes a variety of vehicles, such as 8-seater minibuses and accessible mobility vehicles, ensuring a comfortable ride for everyone.  ',
        'content3' => ' Our services are available 24/7 for your convenience. Book your ride easily through our online booking system on our website and receive an instant quote.'
    ],
    // Add the rest of your destinations here...
];